apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: zone-latam

bases:
  - ../../base

resources:
  - secrets.yaml

configMapGenerator:
  - name: jenkins-agent-config
    behavior: merge
    literals:
      - jenkins-url=http://jenkins.jenkins.svc.cluster.local:8080
      - agent-name=zone-latam

commonLabels:
  region: latam
  agent-name: zone-latam
